;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-semi&comma
        c-electric-slash
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        undo-tree-visualize
        ))
