;;; yang-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from yang-mode.el

(autoload 'yang-mode "yang-mode" "\
Major mode for editing YANG modules.

The hook `c-mode-common-hook' is run with no args at mode
initialization, then `yang-mode-hook'.

Key bindings:
\\{yang-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.yang\\'" . yang-mode))
(register-definition-prefixes "yang-mode" '("yang-"))

;;; End of scraped data

(provide 'yang-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yang-mode-autoloads.el ends here
